### ISSUE TITLE
Non IO way of creating an InetAddress?

### ISSUE THREAD

**Issue by erantapaa** [lpeterse/haskell-socket#19]
It would be nice if there was a way of creating an InetAddress without having to go into the IO-monad. The only way I can see to do it is to use `getAddressInfo`.

I.e. it would be nice to have functions like:

```
createInetAddressV4 :: [Word8] -> InetAddress

createInetAddressV6 :: [Word16] -> InetAddress  -- or use Word8
```

Also see this SO thread: http://stackoverflow.com/q/38770829/866915

**Comment by lpeterse** [comment]
I agree that it's desirable to have such a functions (especially for unit testing etc).

Here are some questions I had in mind when I decided not to supply them:
- What is the most convenient/sensible type signature? You propose `[Word8]` / `[Word16]`, but those are non-total. How to deal with invalid input?
- Is the following (total) too tedious or acceptable?

```
inetCustom :: Word8 -> Word8 -> Word8 -> Word8 -> InetAddress

inet6Custom :: Word16 -> Word16 -> Word16 -> Word16 -> Word16 -> Word16 -> Word16 -> Word16 -> Inet6Address
```

**Comment by erantapaa** [comment]
How about adopting the signatures use by the network package, i.e. see the `tupleToHostAddress` and `tupleToHostAddress6` functions:

https://hackage.haskell.org/package/network-2.6.3.1/docs/Network-Socket.html#v:hostAddressToTuple

There are some other Haskell libraries which deal with IPv4 and IPv6 addresses to compare with - I'll try to dig them up.

**Comment by erantapaa** [comment]
Some other packages to look at:

network-ip: https://hackage.haskell.org/package/network-ip-0.3/docs/Network-IP-Addr.html

ip-route: https://hackage.haskell.org/package/iproute-1.7.0/docs/Data-IP.html#t:IPv4

**Comment by lpeterse** [comment]
I personally like the `tupleToX` and `XtoTuple` from the network package the most.

`ip-route` is non-total. `network-ip` supplies `toWords` and `fromWord`, but they are not exact counter parts wrt. to type signature.

I'd like to add the following to the library:

``` haskell
inetAddressToTuple :: InetAddress -> (Word8, Word8, Word8, Word8)
inetAddressFromTuple :: (Word8, Word8, Word8, Word8) -> InetAddress

inet6AddressToTuple :: Inet6Address -> (Word16,Word16,Word16,Word16,Word16,Word16,Word16,Word16)
inet6AddressFromTuple :: (Word16,Word16,Word16,Word16,Word16,Word16,Word16,Word16) -> Inet6Address
```

Do you agree?

**Comment by erantapaa** [comment]
That's fine. As long as there is a way to construct a value without resorting to IO.

Other people can then create whatever interface they want.

**Comment by lpeterse** [comment]
Just pushed a commit with the additions.

**Comment by lpeterse** [comment]
Changes are in v0.6.2.0 on Hackage.
