### ISSUE TITLE
Build fails on Win 10

### ISSUE THREAD

**Issue by sumo** [lpeterse/haskell-socket#26]
When including socket in a project the build fails with the following:

`ghc.exe: unable to load package `socket-0.6.1.0'
ghc.exe: C:\Users\sumit\AppData\Roaming\stack\snapshots\cae2dc39\lib\x86_64-windows-ghc-8.0.1\socket-0.6.1.0-Jqx8G6Vxk6S4SjRXESQeS8\HSsocket-0.6.1.0-Jqx8G6Vxk6S4SjRXESQeS8.o: unknown symbol `gai_strerrorA'`

Without confirming with the actual MS header - this could be because gai_strerrorA is actually an inline function defined in [ws2tcpip.h](https://sourceforge.net/p/mingw/mingw-org-wsl/ci/5.0-active/tree/w32api/include/ws2tcpip.h#l307).  

Unfortunately I cannot confirm if adding ws2tcpip.h as an include to hs_socket.c fixes the issue as I can't build socket on Win10 currently due to stack not being able to run hsc2hs. Will try this with cabal & ghc once I get them installed tonight.

**Comment by lpeterse** [comment]
Thanks for reporting the issue. I'll try to investigate this and report my findings here.
It would be very valuable to know whether the library and tests itself build and pass in your setup. I validated all versions without problems on Windows so far.

**Comment by lpeterse** [comment]
I set up a fresh Windows 10 Installation with stack and was now able to reproduce the issue (at least in ghci). Building and testing the library itself works, but using it reveals a problem with symbol resolution.

```
lpetersen@... MINGW64 ~/Desktop/haskell-socket (0.8.0.0)
$ stack ghci
Configuring GHCi with the following packages: socket
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
linking extra libraries/objects failed
ghc.EXE: C:\Users\lpetersen\Desktop\haskell-socket\.stack-work\dist\b7fec021\build\platform\win32\cbits\hs_socket.o: unknown symbol `gai_strerrorA'`
```

**Comment by lpeterse** [comment]
Finding number 1: The issue does not occur for simple compiled programs.

Anyway, the function `strerror` does not work for socket exceptions:

```hs
module Main where

import System.Socket

main :: IO ()
main = do
  putStrLn $ "eOk " ++ show eOk
  putStrLn $ "eInterrupted " ++ show eInterrupted
  putStrLn $ "eBadFileDescriptor " ++ show eBadFileDescriptor
  putStrLn $ "eInvalid " ++ show eInvalid
  putStrLn $ "eAddressInUse " ++ show eAddressInUse
  putStrLn $ "eHostUnreachable " ++ show eHostUnreachable
  putStrLn $ "eTimedOut " ++ show eTimedOut
``` 

yields

```
lpetersen@... MINGW64 ~/Desktop/haskell-socket (0.8.0.0)
$ stack ghc -- --make foobar.hs
[1 of 1] Compiling Main             ( foobar.hs, foobar.o )
Linking foobar.exe ...

lpetersen@... MINGW64 ~/Desktop/haskell-socket (0.8.0.0)
$ ./foobar
eOk SocketException "No error"
eInterrupted SocketException "Unknown error"
eBadFileDescriptor SocketException "Unknown error"
eInvalid SocketException "Unknown error"
eAddressInUse SocketException "Unknown error"
eHostUnreachable SocketException "Unknown error"
eTimedOut SocketException "Unknown error"

```

**Comment by VyacheslavHashov** [comment]
Maybe it will help https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/4B603E30.7090702@googlemail.com/

**Comment by lpeterse** [comment]
Oh, nice that you're following.

A while ago I was already working on that issue and tried to use the socket-specific strerror functions on Windows. I got localized error Messages and as I'm natively German speaking I saw that characters like öäü where messed up horribly. I digged deeper about correctly interpreting them as Unicode and I learned about Windows' WIDECHAR etc. Brrrr.  Also, the strerror function I use on Linux is not threadsafe according to the man page.

Do you think it's a viable to solution to just supply pure-Haskell Show instances for the exception types and avoid these obstacles and sources of failure altogether?

**Comment by VyacheslavHashov** [comment]
I think we could have pure haskell strerror, since error codes are almost standart and very rare change.

**Comment by lpeterse** [comment]
Ok. I'll throw them out.
