### ISSUE TITLE
ENOENT error code

### ISSUE THREAD

**Issue by VyacheslavHashov** [lpeterse/haskell-socket#35]
ENOENT is raising on try to connect Unix domain socket to non-existent path in the filesystem.
And i dont know where to put that exception. Possible options:
1) Create module with name `System.Socket.Exception.Unix`, but in requires writing additional import from user.
2) Add exception in the main libary in the `System.Socket.Internal.Exception` despite of the fact this is Unix-specific only.

**Comment by lpeterse** [comment]
I think it is perfectly reasonable to define `eNoEntry` right in `System.Socket.Family.Unix` as it really belongs to the address family aspect of the socket. Even if later moved elsewhere, your module can always still reexport it for convenience.

Adding it to `System.Socket.Internal.Exception` would raise the question to what constant we be bind it on Windows etc. Looks ugly to me, too.

P.S. Besides: Nice work. One more thing I can take off my list ;-)

**Comment by VyacheslavHashov** [comment]
Thanks for the response, I will add it to `System.Socket.Family.Unix` then.
