### ISSUE TITLE
Ptr-base send/receive functions

### ISSUE THREAD

**Issue by VyacheslavHashov** [lpeterse/haskell-socket#41]
With these signatures or similar:
```haskell
send :: Socket f t p -> Ptr Word8 -> Int -> MessageFlags -> IO Int

receive :: Socket f t p -> Ptr Word8 -> Int -> MessageFlags -> IO BS.ByteString
```
They might be useful in the following scenarios:
* Send. The user has a buffer that willing to send and there is no reason to wrap it in ByteString.
* Receive. The user has already allocated a buffer and receiving in it directly prevents extra allocation/copy.

**Comment by VyacheslavHashov** [comment]
There is already `System.Socket.Unsafe`.

**Comment by VyacheslavHashov** [comment]
It is a common practice that exposed functions works with Int, not CInt/CSize because they would be more usable. Is it feasible to rewrite all unsafe functions with accordance to this rule?

**Comment by lpeterse** [comment]
Mhh, open for discussion.

The ByteString library has `useAsCStringLen` where `CStringLen` is an alias for `(Ptr CChar, CSize). I thought it's not too unusual that one rather has a `CSize` than an `Int` when dealing with pointers and having allocated the buffer elsewhere.

> useAsCStringLen :: ByteString -> (CStringLen -> IO a) -> IO a

**Comment by VyacheslavHashov** [comment]
As for example, allocating functions in `Foreign.ForeignPtr` work with `Int`s. But I have taken your point. If a function already has `Ptr` in the signature than changing `CInt` to `Int` gives no appreciable benefit.

**Comment by lpeterse** [comment]
One more point for future readers:

`CSize` is `Word64` whereas an `Int` is only guaranteed to be defined up to 2^29.
