### ISSUE TITLE
How to send ICMP package

### ISSUE THREAD

**Issue by Qinka** [lpeterse/haskell-socket#54]
If I want to send ICMP packages, what should I do? I am a new user in network programming with Haskell.

**Comment by lpeterse** [comment]
Hi,

sending ICMP is not that easy and it depends on what exactly you're trying to do.
You need raw sockets (supported by the library) and assemble the ICMP packets yourself.
Note that a regular user is not allowed to do this by default (at least on Linux) and your process needs the right capability set (see http://unixetc.co.uk/2016/05/30/linux-capabilities-and-ping/ and https://stackoverflow.com/questions/8290046/icmp-sockets-linux).

If you want to use IPPROTO_ICMP (not part of the library) it might make sense to write a separate extension package for this (e.g. `socket-icmp`).

**Comment by Qinka** [comment]
en... Can I just define a type name ICMP, instance type-class Protocol, assemble the ICMP packets, and send it with method send, will that work? Or I need just use type Default, and send packages?
